services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: items
    ports:
      - '3000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '2000:2000'
    depends_on:
      - db
    env_file:
      - .env


volumes:
  postgres_data: 
